services:
  nginx:
    image: nginx:stable-alpine3.20
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/app/web
    ports:
      - 80:80
    restart: always
  php-fpm:
    build:
      target: main
      context: .
    volumes:
      - .:/app
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  postgres:
    image: postgres:17.0-alpine3.20
    volumes:
      - ./var/postgresql/data:/var/lib/postgresql/data
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  worker:
    build:
      target: worker
      context: .
    volumes:
      - .:/app
      - ./etc/supervisor:/etc/supervisor.d
    restart: always
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    entrypoint: [ "supervisord", "--nodaemon" , "--user=root", "--configuration=/etc/supervisord.conf" ]
  deploy:
    build:
      target: deploy
      context: .
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    working_dir: /app
    entrypoint: [ "sh", "deploy.sh" ]
